name       : canta-gtk-theme
version    : 5.17.20
release    : 1
source     :
    - https://github.com/vinceliuice/Canta-theme/archive/2020-05-17.tar.gz : b0a9675471671d3066c93224d7297aa5b2d64261330cf8942d859bbc2a9bc5ca
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Canta is a flat Material Design theme.
description: |
    Canta is a flat Material Design theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments like Gnome, Unity, Budgie, Pantheon, XFCE, Mate, etc.
patterns:
    - compact : /usr/share/themes/*-compact
    - dark : /usr/share/themes/*-dark
    - dark-compact : /usr/share/themes/*-dark-compact
    - light : /usr/share/themes/*-light
    - light-compact : /usr/share/themes/*-light-compact
builddeps  :
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/Canta*/{cinnamon,unity}
    rm -rf $installdir/usr/share/themes/Canta-*/{AUTHORS,COPYING}
