name       : canta-gtk-theme
version    : 2021.09.08
release    : 3
source     :
    - https://github.com/vinceliuice/Canta-theme/archive/refs/tags/2021-09-08.tar.gz : 98f6b71fbc46b1b9e1b256588cf930f780952f95c57f48c9922065c8b333bacd
homepage   : https://github.com/vinceliuice/Canta-theme
license    : GPL-2.0-or-later
component  :
    - desktop.theme
    - compact : desktop.theme
    - dark : desktop.theme
    - dark-compact : desktop.theme
    - light : desktop.theme
    - light-compact : desktop.theme
summary    : Canta is a flat Material Design theme
description: |
    Canta is a flat Material Design theme for GTK 4, GTK 3, GTK 2 and Gnome-Shell. This theme is based on materia gtk theme of nana-4.
patterns   :
    - compact : /usr/share/themes/*-compact
    - dark : /usr/share/themes/*-dark
    - dark-compact : /usr/share/themes/*-dark-compact
    - light : /usr/share/themes/*-light
    - light-compact : /usr/share/themes/*-light-compact
builddeps  :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh -d $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/Canta*/{cinnamon,unity}
    rm -rf $installdir/usr/share/themes/Canta*/{AUTHORS,COPYING}
